export const statesInNigeria = [
	{ key: "1", value: "Abia" },
	{ key: "2", value: "Adamawa" },
	{ key: "3", value: "Akwa Ibom" },
	{ key: "4", value: "Anambra" },
	{ key: "5", value: "Bauchi" },
	{ key: "6", value: "Bayelsa" },
	{ key: "7", value: "Benue" },
	{ key: "8", value: "Borno" },
	{ key: "9", value: "Cross River" },
	{ key: "10", value: "Delta" },
	{ key: "11", value: "Ebonyi" },
	{ key: "12", value: "Edo" },
	{ key: "13", value: "Ekiti" },
	{ key: "14", value: "Enugu" },
	{ key: "15", value: "Gombe" },
	{ key: "16", value: "Imo" },
	{ key: "17", value: "Jigawa" },
	{ key: "18", value: "Kaduna" },
	{ key: "19", value: "Kano" },
	{ key: "20", value: "Katsina" },
	{ key: "21", value: "Kebbi" },
	{ key: "22", value: "Kogi" },
	{ key: "23", value: "Kwara" },
	{ key: "24", value: "Lagos" },
	{ key: "25", value: "Nasarawa" },
	{ key: "26", value: "Niger" },
	{ key: "27", value: "Ogun" },
	{ key: "28", value: "Ondo" },
	{ key: "29", value: "Osun" },
	{ key: "30", value: "Oyo" },
	{ key: "31", value: "Plateau" },
	{ key: "32", value: "Rivers" },
	{ key: "33", value: "Sokoto" },
	{ key: "34", value: "Taraba" },
	{ key: "35", value: "Yobe" },
	{ key: "36", value: "Zamfara" },
	{ key: "37", value: "FCT Abuja" },
];
export const bloodGroupData = [
	{ key: "1", value: "A+" },
	{ key: "2", value: "A-" },
	{ key: "3", value: "B+" },
	{ key: "4", value: "B-" },
	{ key: "5", value: "AB+" },
	{ key: "6", value: "AB-" },
	{ key: "7", value: "O+" },
	{ key: "8", value: "O-" },
];

export const genotypeData = [
	{ key: "1", value: "AA" },
	{ key: "2", value: "AS" },
	{ key: "3", value: "SS" },
	{ key: "4", value: "AC" },
	{ key: "5", value: "SC" },
	{ key: "6", value: "CC" },
];
